# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "LeaveIt"
license = "MIT"
licenselink = "https://github.com/liuzc/LeaveIt/blob/master/LICENSE"
description = "A simple, clean blog theme for hugo."
homepage = "https://liuzhichao.com/"
tags = [
  "blog",
  "minimal",
  "clean",
  "responsive",
  "gallery",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
]
min_version = "0.41"

[author]
  name = "LiuZhichao"
  homepage = "https://liuzhichao.com/"
