baseURL = "http://superssssss.cn/"
languageCode = "zh-CN"
title = "Subranium的小站"

theme = "LeaveIt"

paginate = 12

enableEmoji = true
enableRobotsTXT = true # 支持 robots.txt
hasCJKLanguage = true
preserveTaxonomyNames = true

[author]
  name = "Subranium"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "随手拍"
    url = "/photos/"
    weight = 4
  [[menu.main]]
    name = "总结"
    url = "/summary/"
    weight = 5
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 6

[params]
    since = 2019
    author = "Subranium"
    avatar = "/img/favicon.jpeg"
    subtitle = "我们终此一生，就是要摆脱他人的期待，找到真正的自己。"
    beian = "黑ICP备20002122号-1"
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
    hidecredits = true

[params.social]
    GitHub = "SuperSupeng"
    WeChat = "/img/wechat.jpeg"
    Email = "3529601371@qq.com"

[params.live2d]
    messagePath = "/live2d/"
    homePath   = "http://superssssss.cn/"

[permalinks]
    posts = "/:year/:filename/"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xhtml = false
        [markup.highlight]
            codeFences = true
            guessSyntax = false
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = true
            noClasses = true
            style = "colorful"
            tabWidth = 4
        [markup.tableOfContents]
            endLevel = 3
            ordered = false
            startLevel = 2