# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    
    - name: artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: './public'
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        script: bash /root/del.sh
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        source: "./public"
        target: "/root"
